name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Jenkins docker image
      run: docker build master --tag jenkins:$(date +%s)

    
    - uses: actions/checkout@v2
    - name: Build the Jenkins agent docker image
      run: docker build agent --tag agent:$(date +%s)
