name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Build Jenkins
        uses: docker/build-push-action@v1
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          path: master
          repository: praqma/jcasc
          tag_with_ref: true
          tag_with_sha: true
          
      - name: Build agent
        uses: docker/build-push-action@v1
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          path: agent
          repository: praqma/jcasc-agent
          tag_with_ref: true
          tag_with_sha: true          
   
