name: Update plugins list

on:

  push: 
    branches: [ automatic-upgrade ]
  pull_request:
    branches: [ master, automatic-upgrade ]

jobs:
  upgrade:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Generate new plugins list 
        run: | 
          echo Current plugins versions:
          cat controller/plugins_extra.txt
          echo "*******************************"
          echo New Jenkins Version: $(sh ./jenkins-version.sh)
          echo "*******************************"
          echo Updated plugins versions:
          curl -fsSL -O https://github.com/jenkinsci/plugin-installation-manager-tool/releases/download/2.3.0/jenkins-plugin-manager-2.3.0.jar
          java -jar jenkins-plugin-manager-2.3.0.jar --available-updates --output txt -f controller/plugins_extra.txt --jenkins-version $(sh ./jenkins-version.sh) > plugins.txt
          cp plugins.txt controller/plugins_extra.txt
          git status
