name: Update plugins list

on:

  push: 
    branches: [ automatic-upgrade ]
  pull_request:
    branches: [ master, automatic-upgrade ]

jobs:
  upgrade:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Generate new plugins list 
        run: | 
          curl -fsSL -O https://github.com/jenkinsci/plugin-installation-manager-tool/releases/download/2.3.0/jenkins-plugin-manager-2.3.0.jar
          sh ./jenkins-version.sh
          ls -la 